global:
  labels:
    app: cmstate-operator

deployment:
  labels: {}
  annotations: {}
  pod:
    labels: {}
    annotations: {}
    volumes: []

service:
  name: "cmstate-operator-service"
  labels: {}
  annotations: {}

replicaCount: 1
image:
  repository: public.ecr.aws/x4a1o1q2/cmstate-operator
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

resources: {}

serviceAccount:
  create: true
  name: "cmstate-operator-sa"

webhook:
  labels: {}
  annotations: {}

rbac:
  create: true
  role:
    name: cmstate-operator
    rules:
      - apiGroups: [""]
        resources: ["configmaps"]
        verbs: ["create", "delete", "update", "get", "list", "watch"]
      - apiGroups: ["cache.spices.dev"]
        resources: ["cmstates"]
        verbs: ["create", "delete", "update", "patch", "get", "list", "watch"]
      - apiGroups: ["cache.spices.dev"]
        resources: ["cmstates/finalizers"]
        verbs: ["update"]
      - apiGroups: ["cache.spices.dev"]
        resources: ["cmstates/status"]
        verbs: ["get", "patch", "update"]
      - apiGroups: ["cache.spices.dev"]
        resources: ["cmtemplates"]
        verbs: ["get","list","watch"]
      - apiGroups: ["cache.spices.dev"]
        resources: ["cmtemplates/status"]
        verbs: ["get"]
