apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-internal-role: internal-app
    vault.hashicorp.com/agent-aws-role: ecr_role
    vault.hashicorp.com/agent-configmap: vault-ecr-role
  labels:
    run: nginx
  name: nginx
spec:
  serviceAccountName: "internal-app"
  containers:
    - image: nginx
      name: nginx
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
