apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  namespace:  {{ include .Release.Namespace }}
  labels:
    {{- if or .Values.global.labels }}
    {{ toYaml .Values.global.labels | nindent 4 }}
    {{- end }}
    {{- if .Values.deployment.labels }}
    {{ toYaml .Values.deployment.labels | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
        {{- if or .Values.global.labels }}
        {{ toYaml .Values.global.labels | nindent 8 }}
        {{- end }}
        {{- if .Values.deployment.labels }}
        {{ toYaml .Values.deployment.labels | nindent 8 }}
        {{- end }}
  template:
    metadata:
      labels:
        {{- if or .Values.global.labels }}
        {{ toYaml .Values.global.labels | nindent 8 }}
        {{- end }}
        {{- if .Values.deployment.labels }}
        {{ toYaml .Values.deployment.labels | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
                drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            
