# permissions for end users to view cmstates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cmstate-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cm-injector-operator
    app.kubernetes.io/part-of: cm-injector-operator
    app.kubernetes.io/managed-by: kustomize
  name: cmstate-viewer-role
rules:
- apiGroups:
  - cache.spicedelver.me
  resources:
  - cmstates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.spicedelver.me
  resources:
  - cmstates/status
  verbs:
  - get
