# permissions for end users to edit cmstates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cmstate-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cm-injector-operator
    app.kubernetes.io/part-of: cm-injector-operator
    app.kubernetes.io/managed-by: kustomize
  name: cmstate-editor-role
rules:
- apiGroups:
  - cache.spices.dev
  resources:
  - cmstates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.spices.dev
  resources:
  - cmstates/status
  verbs:
  - get
